name: Build OS image for testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clone the repository AaronDewes/vmdb-config
      run: git clone https://github.com/AaronDewes/vmdb-config.git
    - name: Generate config
      run: ./vmdb-config/create-vmdb2-config -t rpi -o build-blitz-os.vmdb $(realpath build_sdcard.sh)
    - name: Install dependencies
      run: |
              sudo apt-get update
              sudo apt-get install -y cmdtest debootstrap e2fsprogs kpartx parted python3 python3-jinja2 python3-yaml qemu-utils qemu-user-static rsync wget
    - name: Install vmdb2 from git and build
      run: |
              git clone https://gitlab.com/larswirzenius/vmdb2.git
              # We're not caching the rootfs and rebuild it every time, but we still need to set a cache file
              sudo vmdb2/vmdb2 --output rpi.img --rootfs-tarball ./cache-tarball build-blitz-os.vmdb
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: blitz-test-os
        path: ./rpi.img

